name: Generate Snake

# 触发条件：每天零点自动运行，或者手动点击运行
on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          # 这里会自动读取你的用户名
          github_user_name: ${{ github.repository_owner }}
          # 输出生成的图片到 dist 文件夹
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 将生成的图片推送到 output 分支
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
